### ISSUE TITLE
lsws license breaks when docker container is being rebuild

### ISSUE THREAD

**Issue by PiotrCzapla** [litespeedtech/lsws-docker-env#5]
Hi
After rebuilding a docker container I'm getting this error
> Server signature does not match the license key #3.
> Please request a new license key!

I think I've solved that by removing the license key and requesting it again but that will be an issue if i run this setup in production as it will slow down upgrades

**Comment by Code-Egg** [comment]
Hi,

The current logic is if the server has a serial key or license key, then build/rebuild will not request a new trial key. 

So you won't hit the issue if this is in production, here's the doc for applying license.
https://docs.litespeedtech.com/cloud/docker/magento/#applying-license-to-lsws
```
bash bin/webadmin.sh [-S, --serial] YOUR_SERIAL
```

**Comment by PiotrCzapla** [comment]
Yeah, the trial is not requested, but the license stop working after rebuild, as the host name of docker container changes.

**Comment by Code-Egg** [comment]
May I know your rebuild command? 
I tried `docker-compose up --build -d` on my test server, but the service is still working fine.

**Comment by PiotrCzapla** [comment]
It complains then it refetches the license, I haven't noticed that. Sorry for not testing fully.

**Comment by Code-Egg** [comment]
No problem
