### ISSUE TITLE
Upgrade path for live environment

### ISSUE THREAD

**Issue by PiotrCzapla** [litespeedtech/lsws-docker-env#7]
Hi,

Do you have some thoughts how to upgrade the dockerised lsws on a production environment, with minimal downtime?
I was thinking about spanning new instance on the same box different ports test it locally then switching to the it using firewall once testing is done. But I'm not sure if I won't run in to problems and since, the software needs license I will have troubles to test it on a separate server. So I would appreciate help.

I see that the docker container updates it self automatically to minor version. I hope it wont do the upgrade to a major release automatically.

**Comment by PiotrCzapla** [comment]
Although I have doubts that the upgrade was successful, as there is no binary files of lsws changed.
```
docker diff xxxxxxxxxxxxxxx
C /run
C /run/lshttpd.pid
C /tmp
C /tmp/lshttpd
A /tmp/lshttpd/xxxx.pl_lsphp.sock.766
C /tmp/lshttpd/lshttpd.pid
C /tmp/lshttpd/swap
A /tmp/lshttpd/swap/* 
C /tmp/lshttpd/.rtreport
C /tmp/lshttpd/.status
A /tmp/lshttpd/beta.xxxx.pl_lsphp.sock
A /tmp/magick-xxxxxxxxxxxxxxx
A /tmp/wsdl-nobody-xxxxxxxxxxxxxxx
C /root
A /root/.bash_history
C /var
C /var/log
C /var/log/newrelic
A /var/log/newrelic/php_agent.log
C /usr
C /usr/local
C /usr/local/lsws
C /usr/local/lsws/admin
C /usr/local/lsws/admin/logs
C /usr/local/lsws/admin/logs/access.log
C /usr/local/lsws/admin/logs/error.log
C /usr/local/lsws/admin/cgid
A /usr/local/lsws/admin/cgid/cgid.sock.xxxxxxx
C /usr/local/lsws/admin/cgid/secret
A /usr/local/lsws/admin/cgid/secret/cgid.sock.xxxxxxx
C /usr/local/lsws/admin/tmp
A /usr/local/lsws/admin/tmp/admin.sock.7760
A /usr/local/lsws/admin/tmp/sess_xxxxxxxxxxxxxxxxxxxxxxxxx
C /usr/local/lsws/admin/tmp/.lsphp_restart.txt
C /usr/local/lsws/autoupdate
A /usr/local/lsws/autoupdate/.last
A /usr/local/lsws/autoupdate/platform
A /usr/local/lsws/autoupdate/release
A /usr/local/lsws/autoupdate/update.log
```

I though the diff would show some binary files in lsws/ changed.

**Comment by Code-Egg** [comment]
Hi @PiotrCzapla ,

If you only want to upgrade LSWS, try the following command to upgrade to the latest stable version which should have no downtime. 
```
bash bin/webadmin.sh -U
```
More info, https://docs.litespeedtech.com/cloud/docker/magento/#updating-web-server

Let me know if this is not the solution that you are looking for.
