### ISSUE TITLE
license error

### ISSUE THREAD

**Issue by farbodpm** [litespeedtech/lsws-docker-env#8]
I used 15 day trial and then I changed one of my old license ip to this server but litespeed container failes.

ws-docker-env-litespeed-1  | [FATAL] license problem, back to Apache!
lsws-docker-env-litespeed-1  | [ERROR] Failed to start litespeed!
lsws-docker-env-litespeed-1  | --2022-09-19 03:19:47--  http://license.litespeedtech.com/reseller/trial.key
lsws-docker-env-litespeed-1  | Resolving license.litespeedtech.com (license.litespeedtech.com)... 135.148.138.120
lsws-docker-env-litespeed-1  | Connecting to license.litespeedtech.com (license.litespeedtech.com)|135.148.138.120|:80... connected.
lsws-docker-env-litespeed-1  | HTTP request sent, awaiting response... 200 OK
lsws-docker-env-litespeed-1  | Length: 256 [application/octet-stream]
lsws-docker-env-litespeed-1  | Saving to: '/usr/local/lsws/conf/trial.key'
lsws-docker-env-litespeed-1  |
lsws-docker-env-litespeed-1  |      0K                                                       100% 11.3M=0s
lsws-docker-env-litespeed-1  |
lsws-docker-env-litespeed-1  | 2022-09-19 03:19:47 (11.3 MB/s) - '/usr/local/lsws/conf/trial.key' saved [256/256]
lsws-docker-env-litespeed-1  |
lsws-docker-env-litespeed-1  | 2022-09-19 03:19:48.381457 [NOTICE] Memory size is: 8151784KB.
lsws-docker-env-litespeed-1  | 2022-09-19 03:19:49.104877 [ERROR] [LICENSE] License key operation failure: ERR LC.VT: Your trial period has terminated. Please contact sales if you need to extend your trial.
lsws-docker-env-litespeed-1  | [FATAL] license problem, back to Apache!
lsws-docker-env-litespeed-1  | [ERROR] Failed to start litespeed!
lsws-docker-env-litespeed-1  | [ERROR] Failed to find your license key under - /usr/local/lsws/ or /usr/local/lsws/conf/!
lsws-docker-env-litespeed-1  | [ERROR] Failed to find your license key under - /usr/local/lsws/ or /usr/local/lsws/conf/!
lsws-docker-env-litespeed-1  | [FATAL] license problem, back to Apache!
lsws-docker-env-litespeed-1  | [ERROR] Failed to start litespeed!

how should I reset the docker so that license change be okay.

**Comment by Code-Egg** [comment]
it seems using an expired trial license so it failed to start. Have you tried the following command to switch the license?
```
bash bin/webadmin.sh [-S, --serial] YOUR_SERIAL
```
then start the service again with `docker-compose up --build -d`.
