### ISSUE TITLE
htpasswd: Permission denied

### ISSUE THREAD

**Issue by ConnersHua** [litespeedtech/lsws-docker-env#9]
Hello

when I run
```bash
bash bin/webadmin.sh my_password
```
```bash
Update web admin password.
bash: line 3: /usr/local/lsws/admin/conf/htpasswd: Permission denied
```

I tried to modify `.env` back to
```bash
LSWS_VERSION=6.0.12
PHP_VERSION=lsphp81
```
```bash
Update web admin password.
```

It seems to have succeeded, and the `.env` file has been modified back to the new version, but the webadmin login is unresponsive

any tips? thank you

**Comment by Code-Egg** [comment]
Thanks for the report. The [latest commit](https://github.com/litespeedtech/lsws-dockerfiles/commit/8be31ccb0a2826f3c7700edc90827beb04e5226e) should have it fixed. Please try the new LSWS image again and see if it helps. 
Note, remember to remove the existing one e.g. `docker rmi litespeedtech/litespeed:6.3.1-lsphp83`

**Comment by ConnersHua** [comment]
Thank you very much
